services:
    sim_trans_form.mapper:
        class:     Simettric\DoctrineTranslatableFormBundle\Form\DataMapper
        arguments: ["@doctrine.orm.entity_manager"]
    doctrine.translatable.locale_listener:
        class: Simettric\DoctrineTranslatableFormBundle\EventListener\LocaleListener
        arguments:
            - "%settings%"
            - "@translator"
            - "@kernel"
        tags:
            - { name: kernel.event_subscriber }